global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['<NODE_EXPORTER_IP>:9100']

alerting:
alertmanagers:
  - static_configs:
      - targets: ['localhost:9093']