[package]
name = "api"
version = "0.1.0"
edition = "2018"

[dependencies]
near-sdk = "3.1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
borsh = "0.8.2"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
panic = "abort"
lto = true